version: '3'

services:
  sshstatus:
    image: dkllrjr/sshstatus:latest
    restart: unless-stopped
    ports:
      - 9429:9429
    volumes:
      - "./config.yml:/app/config.yml"
    environment:
      CHECK_TIMEOUT: $CHECK_TIMEOUT
      TCP_TIMEOUT: $TCP_TIMEOUT
